### ISSUE TITLE
Kanban Board: Cargogo

### ISSUE THREAD

**Issue by RiyaBulia12** [RiyaBulia12/Cargogo-front-end#17]
Project Theme: Rent a Car (Since some of the members are repeating the project, we are working on the second project requirement)
Project Description: https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/buisness_requirements_2.md
Board Link: https://github.com/users/RiyaBulia12/projects/8/views/1

Frontend Project: https://github.com/RiyaBulia12/Cargogo-front-end/
Backend Project: https://github.com/shyusu4/CarGoGo-Backend/

#### Members Name:
- @RiyaBulia12 
- @Roseokpe 
- @zemola 
- @shyusu4 

#### Screenshot of the board
<img width="1440" alt="Screenshot 2023-01-25 at 4 12 24 PM" src="https://user-images.githubusercontent.com/24832846/214542828-bf8473a2-1909-48db-aec9-2273962d2d91.png">

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
